### ISSUE TITLE
书中代码缺失？

### ISSUE THREAD

**Issue by SUMARKER** [sg552/happy_book_vuejs#3]
p64 4.4 中的实例看着不像是一个demo里取的，
路由目录没有说清，而且{{ message }} 也没有地方声明。

**Comment by SUMARKER** [comment]
p67  4.5.1 控制语句 return a; 没有空格

**Comment by woshihuangshuai** [comment]
p54 步骤2只有注释没有代码

**Comment by sg552** [comment]
非常抱歉, 不是盗版, 是我的失误.
请留下您的支付宝或者微信号码, 我把您买书的费用转过来. 

入门的话,看这个github的简单版也可以了, 或者 http://vue_book.siwei.me/
