### ISSUE TITLE
不知道是不是买到盗版了

### ISSUE THREAD

**Issue by woshihuangshuai** [sg552/happy_book_vuejs#4]
京东上买的，书中印刷错误多的出奇

**Comment by sg552** [comment]
非常抱歉, 不是盗版, 是我的失误.
请留下您的支付宝或者微信号码, 我把您买书的费用转过来.

**Comment by woshihuangshuai** [comment]
> 非常抱歉, 不是盗版, 是我的失误.
> 请留下您的支付宝或者微信号码, 我把您买书的费用转过来.

不必了。虽然书中的错误，让我在读的过程中有点难受，但是我学习vue的第一本书，确实有帮到我这个前端小白，感谢
